# Generated by Django 4.2.6 on 2023-10-22 20:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=70)),
                ('product_description', models.CharField(max_length=300)),
                ('product_starting_bid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_inserted', models.DateField()),
                ('date_sold', models.DateField(default=datetime.date.today)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
