# Generated by Django 4.2.6 on 2023-10-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_product_product_img_url_alter_product_date_inserted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_sold',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
