# Generated by Django 4.2.6 on 2023-10-22 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_auctions_auction_rename_comments_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='Amount_bid',
            new_name='amount_bid',
        ),
        migrations.AddField(
            model_name='auction',
            name='winning_bid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='product_comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auctions.product'),
            preserve_default=False,
        ),
    ]
