# Generated by Django 4.2.6 on 2023-10-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_product2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='product_sold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='auctions.product'),
        ),
    ]
