# Generated by Django 4.2.6 on 2023-10-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_auction_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='status_bid',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=20),
        ),
    ]
