# Generated by Django 4.2.6 on 2023-10-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auction_status_bid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product2',
        ),
    ]
