# Generated by Django 4.2.6 on 2023-10-26 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_product_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='date_bid',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
