# Generated by Django 4.2.6 on 2023-11-01 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='product_watchlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_watched', to='auctions.product'),
        ),
    ]
